<!DOCTYPE html>
<html lang="{{ $locale ?? 'en' }}">
<head>
    <meta charset="utf-8">
    <title>{{ $seoTitle ?? $title }}</title>
    <style>
        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 12pt;
            line-height: 1.6;
            color: #333;
            padding: 20px;
        }
        h1 {
            font-size: 22pt;
            margin-bottom: 5px;
            color: #111;
        }
        h2 { font-size: 16pt; margin-top: 20px; color: #222; }
        h3 { font-size: 14pt; margin-top: 15px; color: #333; }
        p { margin: 8px 0; }
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 12px 0;
        }
        th, td {
            border: 1px solid #ccc;
            padding: 6px 10px;
            text-align: left;
        }
        th {
            background: #f5f5f5;
            font-weight: bold;
        }
        code {
            background: #f0f0f0;
            padding: 1px 4px;
            border-radius: 3px;
            font-size: 10pt;
        }
        pre {
            background: #f5f5f5;
            padding: 10px;
            border: 1px solid #ddd;
            border-radius: 4px;
            font-size: 10pt;
            overflow-x: auto;
        }
        blockquote {
            border-left: 3px solid #ccc;
            margin: 10px 0;
            padding-left: 12px;
            color: #666;
        }
        .footer {
            margin-top: 30px;
            padding-top: 10px;
            border-top: 1px solid #ddd;
            font-size: 9pt;
            color: #999;
            text-align: center;
        }
        ul, ol {
            margin: 8px 0;
            padding-left: 20px;
        }
        .watermark {
            position: fixed;
            z-index: 9999;
            pointer-events: none;
            opacity: {{ config('blogr-docs.pdf.watermark.opacity', 0.2) }};
            font-size: 60px;
            color: #999;
            transform: rotate(-45deg);
            @if(config('blogr-docs.pdf.watermark.position', 'center') === 'center')
                top: 50%; left: 50%; margin-left: -200px; margin-top: -100px; width: 400px; text-align: center;
            @elseif(config('blogr-docs.pdf.watermark.position', 'center') === 'top-left')
                top: 40px; left: 40px;
            @elseif(config('blogr-docs.pdf.watermark.position', 'center') === 'top-right')
                top: 40px; right: 40px;
            @elseif(config('blogr-docs.pdf.watermark.position', 'center') === 'bottom-left')
                bottom: 40px; left: 40px;
            @elseif(config('blogr-docs.pdf.watermark.position', 'center') === 'bottom-right')
                bottom: 40px; right: 40px;
            @endif
        }
        .watermark img {
            max-width: 300px;
            max-height: 300px;
        }
    </style>
</head>
<body>
    @if(config('blogr-docs.pdf.watermark.enabled', false))
        <div class="watermark">
            @if(config('blogr-docs.pdf.watermark.image'))
                <img src="{{ public_path(config('blogr-docs.pdf.watermark.image')) }}" alt="">
            @else
                {{ config('blogr-docs.pdf.watermark.text', 'Confidential') }}
            @endif
        </div>
    @endif

    <h1>{{ $title }}</h1>
    @if(!empty($seoDescription))
        <p style="font-size: 11pt; color: #666; margin-bottom: 20px;">{{ $seoDescription }}</p>
    @endif

    {!! $content !!}

    <div class="footer">
        Generated by Blogr Docs — {{ date('Y-m-d') }}
    </div>
</body>
</html>
